name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go fmt ./...
      - run: go test -v ./...
      - name: Test Run netnsplan
        run: |
          go build -o netnsplan
          ./netnsplan -h
          ./netnsplan apply -d .github/testdata
